### ISSUE TITLE
Close stale Pull Requests

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#10565]
### Feature Description

When a Pull Request has been stale for a long time, we should warn the author by automatically commenting on it. If after a delay the Pull Request is still stale, we should automatically close it.

There are bots that can achieve this in the GitHub Marketplace.

### Use Case(s)

Let's say someone creates a Pull Request, it gets reviewed and some changes are required, if after `x` weeks or months the author has not come back to the Pull Request and made the required changes, we would automatically comment the Pull Request. This will allow the author and participants to receive a notification about the Pull Request. If no one takes action on the Pull Request after a delay, let's say 7 days, we would automatically close the Pull Request.

If the author or someone else needs, they can always re-open the Pull Request.

**Comment by ajm188** [comment]
I think we should look at the official (? maybe, it's under their org) [github/stale](https://github.com/actions/stale) action. Based on my read we want the following config:

```yaml
# 1 month of no activity, or, for us, "one third of a release cycle"
days-before-stale: 30
# Never mark issues as stale.
days-before-issue-stale: -1
# Close 7 days after transitioning to Stale. This is the default, so technically we don't need to specify.
days-before-close: 7

stale-pr-message: TODO, work on wording, but we should set this
close-pr-message: TODO, work on wording, but we should set this

# This is the default value. We'll need to create this label in the vitess repo.
stale-pr-label: Stale

# This defaults to false, but i think we should talk about whether we want to close drafts (I'm not sure!).
# Note also the docs specify a big warning that we should take into account: https://github.com/actions/stale#exempt-draft-pr
exempt-draft-pr: true
```
