### ISSUE TITLE
how to config vitess operator backup local volume

### ISSUE THREAD

**Issue by alexchenfeng** [vitessio/vitess#10678]
### Question

I'm using vitess operator start with 101_initial_cluster.yaml, I want to config a backup local volume storage, the config as below:

```
...

  backup:
    engine: xtrabackup
    locations:
      - volume:
          hostpath:
            path: /mfs/vitess-db-backup
            type: DirectoryOrCreate
...
```

but when I  check "kubectl get vitessbackupstorages.planetscale.com", the result of backup data path is empty. where I was wrong? how to config volume backup in 101_initial_cluster.yaml? Thank you.

**Comment by GuptaManan100** [comment]
Could you provide a little more detail as to what steps you are taking and what output you are seeing so that we can help you diagnose the problem? We have an end-to-end test that tests backups and restores here at https://github.com/planetscale/vitess-operator/blob/main/test/endtoend/backup_restore_test.sh. It might be useful to take a look at the test.

https://github.com/planetscale/vitess-operator/blob/main/test/endtoend/operator/101_initial_cluster_backup.yaml is the configuration we use in the test.
The config has a very similar yaml setup: 
```yaml
spec:
  backup:
    engine: xtrabackup
    locations:
    - volume:
        hostPath:
          path: /backup
          type: Directory
```

When I run that test and check that outputs for the resources I see - 
```
 ~/vitess-operator/test/endtoend/operator   main ±  kubectl get vitessbackupstorages.planetscale.com
NAME               AGE
example-90089e05   78s
```
and 
```
 ~/vitess-operator/test/endtoend/operator   main ±  kubectl describe vitessbackupstorages.planetscale.com example-90089e05
Name:         example-90089e05
Namespace:    default
Labels:       backup.planetscale.com/location=
              planetscale.com/cluster=example
Annotations:  <none>
API Version:  planetscale.com/v2
Kind:         VitessBackupStorage
Metadata:
  Creation Timestamp:  2022-07-14T05:51:05Z
  Generation:          1
  Managed Fields:
    API Version:  planetscale.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:backup.planetscale.com/location:
          f:planetscale.com/cluster:
        f:ownerReferences:
          .:
          k:{"uid":"bca62f83-0aae-4794-8855-872147bb78a5"}:
      f:spec:
        .:
        f:location:
          .:
          f:volume:
            .:
            f:hostPath:
              .:
              f:path:
              f:type:
    Manager:      vitess-operator
    Operation:    Update
    Time:         2022-07-14T05:51:05Z
    API Version:  planetscale.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:observedGeneration:
        f:totalBackupCount:
    Manager:      vitess-operator
    Operation:    Update
    Subresource:  status
    Time:         2022-07-14T05:52:10Z
  Owner References:
    API Version:           planetscale.com/v2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VitessCluster
    Name:                  example
    UID:                   bca62f83-0aae-4794-8855-872147bb78a5
  Resource Version:        1286
  UID:                     9da2e7ed-bba3-4702-886a-bb80aaeea365
Spec:
  Location:
    Volume:
      Host Path:
        Path:  /backup
        Type:  Directory
Status:
  Observed Generation:  1
  Total Backup Count:   1
Events:
  Type    Reason   Age   From                               Message
  ----    ------   ----  ----                               -------
  Normal  Created  98s   vitessbackupstorage-controller     created Pod example-90089e05-vitessbackupstorage-subcontroller
  Normal  Created  33s   vitessbackupstorage-subcontroller  created VitessBackup example-commerce-x-x-20220714-055208-76817e0-966ce9e9
```

What version of the operator are you using? Is there something that you are doing different from the test?

**Comment by fengchenu** [comment]
Confusing, my yaml config file:

```
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  backup:
    engine: xtrabackup
    locations:
    - volume:
        hostpath:
          path: /mfs/vitess-invisibleart-web-zone1-db-backup
          type: Directory

  images:
    vtctld: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
    vtgate: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
    vttablet: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
    vtbackup: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
    mysqld:
      mysql80Compatible: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
    mysqldExporter: 192.168.1.114:5000/prom/mysqld-exporter:v0.14.0
```
the different of my custom file with 101_initial_cluster.yaml:

```
--- 101_initial_cluster.yaml    2022-07-14 17:43:15.000000000 +0800
+++ ../operator-example/101_initial_cluster.yaml        2022-07-10 22:50:59.000000000 +0800
@@ -7,22 +7,14 @@
 metadata:
   name: example
 spec:
-  backup:
-    engine: xtrabackup
-    locations:
-    - volume:
-        hostpath:
-          path: /mfs/vitess-invisibleart-web-zone1-db-backup
-          type: Directory
-
   images:
-    vtctld: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
-    vtgate: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
-    vttablet: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
-    vtbackup: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
+    vtctld: vitess/lite:v14.0.0
+    vtgate: vitess/lite:v14.0.0
+    vttablet: vitess/lite:v14.0.0
+    vtbackup: vitess/lite:v14.0.0
     mysqld:
-      mysql80Compatible: 192.168.1.114:5000/vitess/percona-lite:v8.0.28-20
-    mysqldExporter: 192.168.1.114:5000/prom/mysqld-exporter:v0.14.0
+      mysql56Compatible: vitess/lite:v14.0.0
+    mysqldExporter: prom/mysqld-exporter:v0.11.0
```
