### ISSUE TITLE
Peridic backups

### ISSUE THREAD

**Issue by javaboboApp** [vitessio/vitess#11934]
### Question

Hi I just started using vitess and I am surprised that there is not an easy way to run period backups. For example, run backups every 24 hours.

I was cheking documentation: https://vitess.io/docs/16.0/user-guides/operating-vitess/backup-and-restore/creating-a-backup/ 

I could not find anything about it , so it is quite disappointing. I tried to use **vtbackup** but is not clear to me how I can archive this. Also I thought in using a cronJob in kuberntetes similar to: 

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - HERE COMMAND TO RUN A BACKUPS
          restartPolicy: OnFailure
```

Any suggestions on how I can create a period backup tasks?

**Comment by javaboboApp** [comment]
I was able to do it, creating an image using the next Docker file: 

```
# First stage: build the Go binary
FROM golang:latest as builder

# Set the working directory
WORKDIR /go/src/myproject

# Copy the source files
COPY . .


FROM ubuntu:latest

# Copy the built binary from the builder stage
COPY --from=builder /go/src/myproject .

# Set the GOPATH environment variable and add it to PATH
ENV GOPATH go
ENV PATH $GOPATH/bin:$PATH

RUN apt-get update && \
    apt-get install -y wget tar && \
    wget https://github.com/vitessio/vitess/releases/download/v15.0.1/vitess-15.0.1-13ee9c8.tar.gz && \
    tar xzvf vitess-15.0.1-13ee9c8.tar.gz && \
    cd  vitess-15.0.1-13ee9c8 && \
    mkdir -p /usr/local/vitess && \ 
    cp -r * /usr/local/vitess/
 


ENV PATH="/usr/local/vitess/bin:${PATH}" 


CMD ["sleep", "infinity"]

```

And using a CronJob


```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cron-job
spec:
  schedule: "0 0 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vitesscontainer
            image: {image}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - vtctlclient --server={service_name}:15999 --logtostderr BackupShard apidbtest3/-  
          restartPolicy: OnFailure
         
```

Anyway, it would be good to have a way to configure autobackups: 

1) Delete backups after x days (saving space)
2) Delete previous backups using the utility command.
