### ISSUE TITLE
Bug Report: Vttestserver docker image command doesn't work

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#12003]
### Overview of the Issue

The command listed on the website docs `docker run --name=vttestserver -p 33577:33577 -e PORT=33574 -e PLANNER_VERSION=gen4fallback -e KEYSPACES=test,unsharded -e NUM_SHARDS=2,1 -e MYSQL_MAX_CONNECTIONS=70000 -e MYSQL_BIND_HOST=0.0.0.0 --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5 vitess/vttestserver:mysql57
` doesn't work with the vttestserver docker image.

An error like this is thrown - 
```
ERROR: logging before flag.Parse: E1221 11:44:07.749554      16 syslogger.go:149] can't connect to syslog
invalid argument "" for "--tablet_refresh_interval" flag: time: invalid duration ""
Usage of /vt/bin/vttestserver:
      --alsologtostderr                                                  log to standard error as well as files
      --app_idle_timeout duration                                        Idle timeout for app connections (default 1m0s)

```

### Reproduction Steps

Build the docker image of `vttestserver` and run the docker command

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
main
```

**Comment by GuptaManan100** [comment]
This problem seems to have been introduced in https://github.com/vitessio/vitess/pull/11918

**Comment by Jolg42** [comment]
I also have the same issue.

For me using
```
version: '3.7'
  vitess-8:
    image: vitess/vttestserver:mysql80
    restart: always
    ports:
      - 33807:33807
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P33577']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 25s
    environment:
      PORT: '33804'
      KEYSPACES: 'unsharded' 
      NUM_SHARDS: '1' 
      MYSQL_BIND_HOST: '0.0.0.0'
      FOREIGN_KEY_MODE: 'disallow'
```

Used to work before and now errors when doing `docker-compose up -d vitess-8`

Relevant error from the logs:
```
2022-12-21 13:06:13 /vt/run.sh: line 46: --schema_dir=/vt/schema/: No such file or directory
2022-12-21 13:06:26 mkdir: cannot create directory '/vt/schema/': File exists
2022-12-21 13:06:26 mkdir: cannot create directory '/vt/schema/unsharded': File exists
2022-12-21 13:06:26 ERROR: logging before flag.Parse: E1221 12:06:26.514986      27 syslogger.go:149] can't connect to syslog
2022-12-21 13:06:26 invalid argument "" for "--tablet_refresh_interval" flag: time: invalid duration ""
```

_Originally posted by @Jolg42 in https://github.com/vitessio/vitess/issues/11868#issuecomment-1361249864_
