### ISSUE TITLE
Bug Report: vttablet parameter doesn't accepts values as described

### ISSUE THREAD

**Issue by Areso** [vitessio/vitess#12719]
### Overview of the Issue

```
--grpc_max_message_size int                                        Maximum allowed RPC message size. Larger messages will be rejected by gRPC with the error 'exceeding the max size'. (default 16777216)
```
that's what I see in the output of the vttablet flags.

Okay, looks reasonable.
Part of my cluster definition:
```
              - cell: eucentral1b
                type: replica
                replicas: 1
                vttablet:
                  extraFlags:
                    grpc_max_message_size: 134217728
                  resources:
                    requests:
                      cpu: 300m
                      memory: 512Mi
                    limits:
                      memory: 512Mi
                mysqld:
                  configOverrides: |
                    max_allowed_packet = 134217728
                  resources:
                    requests:
                      cpu: 1600m
                      memory: 1Gi
                dataVolumeClaimTemplate:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: "io2-10k"
                  resources:
                    requests:
                      storage: 50Gi
```
when I try to apply the cluster definition, I am getting the following error:
```
knv apply -f cluster_k8s-mysql.yml 
The VitessCluster "test" is invalid: spec.keyspaces.partitionings.custom.shards.tabletPools.vttablet.extraFlags.grpc_max_message_size: Invalid value: "integer": spec.keyspaces.partitionings.custom.shards.tabletPools.vttablet.extraFlags.grpc_max_message_size in body must be of type string: "integer"
```

### Reproduction Steps

Add to your cluster def under the vttablet the following:
```
                vttablet:
                  extraFlags:
                    grpc_max_message_size: 134217728
```
try to apply 
```
knv apply -f cluster_k8s-mysql.yml 
The VitessCluster "test" is invalid: spec.keyspaces.partitionings.custom.shards.tabletPools.vttablet.extraFlags.grpc_max_message_size: Invalid value: "integer": spec.keyspaces.partitionings.custom.shards.tabletPools.vttablet.extraFlags.grpc_max_message_size in body must be of type string: "integer"
```

### Binary Version

```sh
16.0.0
```

### Operating System and Environment details

```sh
EKS, 1.23
```
