### ISSUE TITLE
Bug Report: vtctldclient vdiff incorrectly limits rows

### ISSUE THREAD

**Issue by mattlord** [vitessio/vitess#14777]
### Overview of the Issue

The new [`vtctldclient vdiff` implementation](https://github.com/vitessio/vitess/pull/13976) (added in v18) incorrectly limits the maximum rows diffed per table to the [`max-extra-rows-to-compare` flag](https://vitess.io/docs/reference/programs/vtctldclient/vtctldclient_vdiff/vtctldclient_vdiff_create/) value (default: 1000).

### Reproduction Steps

```
git checkout main && make build

cd examples/local

./101_initial_cluster.sh; mysql < ../common/insert_commerce_data.sql; ./201_customer_tablets.sh; ./202_move_tables.sh

for i in {1..10}; do echo mysql commerce -e "insert into customer (email) values ('${RANDOM}_person_${RANDOM}@planetscale.com'); insert into customer (email) select email from customer;"; done

vtctldclient vdiff --target-keyspace customer --workflow commerce2customer create

sleep 10

vtctldclient vdiff --target-keyspace customer --workflow commerce2customer show last

command mysql -u root --socket=${VTDATAROOT}/vt_0000000201/mysql.sock -e "select * from _vt.vdiff\G"
```

If you look at the vdiff record on the target side, you'll see that the max_rows core option is set to 1,000:
```
mysql> select * from _vt.vdiff\G
*************************** 1. row ***************************
                id: 1
        vdiff_uuid: 95741c3f-b465-429d-b770-ad54a4ed0ddb
          workflow: commerce2customer
          keyspace: customer
             shard: 0
           db_name: vt_customer
             state: completed
           options: {"core_options": {"max_rows": 1000, "auto_retry": true, "timeout_seconds": 30, "max_extra_rows_to_compare": 1000}, "picker_options": {"source_cell": "zone1", "target_cell": "zone1", "tablet_types": "in_order:rdonly,replica,primary"}, "report_options": {"max_sample_rows": 10}}
        created_at: 2023-12-13 14:10:04
        started_at: 2023-12-13 19:10:04
liveness_timestamp: NULL
      completed_at: 2023-12-13 19:10:04
        last_error:
```

### Binary Version

```sh
vtgate version Version: 19.0.0-SNAPSHOT (Git revision 5ee1b9b735f09c54a19177c1d6dd2b08e0fad136 branch 'main') built on Wed Dec 13 15:26:40 EST 2023 by matt@pslord.local using go1.21.5 darwin/arm64
```

### Operating System and Environment details

```sh
N/A
```
