### ISSUE TITLE
Bug Report: Broken charset response when establishing MySQL connection to Vitess 19

### ISSUE THREAD

**Issue by GrahamCampbell** [vitessio/vitess#15112]
### Overview of the Issue

Unable to connect to Vitess 19 using PHP PDO (as used by all the major frameworks including Laravel). This issue is not present on Vitess 18.

### Reproduction Steps

Connect to a fresh copy of `vitess/vttestserver:mysql80`, for example using docker compose config:

```yaml
  db:
    image: vitess/vttestserver:mysql80
    command: "/vt/bin/vttestserver --alsologtostderr --port=33574 --mysql_bind_host=0.0.0.0 --keyspaces=test --num_shards=1"
    networks:
      - voxie
    ports:
      - "33577:33577"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P33577']
      interval: 5s
      timeout: 2s
      retries: 20
```

Connect to the server using PHP PDO. For example, using any version of PHP 8 compiled with MySQL PDO support:

```php
<?php

new PDO(
    'mysql:host=127.0.0.1;port=33577;dbname=test',
    'root',
    '',
);
```

Running the file (`php test.php`) results in the following crash:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers
```

### Binary Version

vtgate is not present within the Docker image, but vtcombo is.

```sh
vtcombo version Version: 19.0.0-SNAPSHOT (Git revision 6f9c5c2ffed3be3416198b9de4c49323b946c0e5 branch 'main') built on Thu Feb  1 15:26:02 UTC 2024 by vitess@buildkitsandbox using go1.21.6 linux/amd64
```

### Operating System and Environment details

Running within Docker on MacOS. Results from within the running container:

```sh
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```sh
Linux 6.6.12-linuxkit
```

```
x86_64
```
