### ISSUE TITLE
Feature Request: support private go packages

### ISSUE THREAD

**Issue by timvaillancourt** [vitessio/vitess#16018]
### Feature Description

This issue proposes that the GitHub Actions workflows and Docker-based builds support the use of Golang packages in private Git(Hub) repos, in order to allow users with custom durability policies in private repos to smoothly build Vitess

Today Slack applies these patches to our fork to achieve this, but having this supported upstream would probably benefit other users with a fork and a custom durability policy:
1. https://github.com/slackhq/vitess/pull/266
2. https://github.com/slackhq/vitess/pull/367

The meat of this change would be including the following in `.github/workflow` files (made by `test/templates` files):
```yaml
    - name: Setup github.com/slackhq/vitess-additions access token
      run: git config --global url.https://${{secrets.GH_ACCESS_TOKEN}}@github.com/.insteadOf https://github.com/
      if: ${{secrets.GH_ACCESS_TOKEN}} != ""
```
Where `${{secrets.GH_ACCESS_TOKEN}}` is a GitHub Secret a user sets in their fork. It's possible `GOPRIVATE` needs to be set too

On the Docker-build side, adding the ability to pass the token into the build will be required, via: `--build-arg GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN}`. Finally, `Dockerfile`s will need to be updated to run a similar `git config` command as the CI

### Use Case(s)

Users that have a custom Durability Policy in a private git-repo, which admittedly is probably a small group, but this may change if the interface concept is adopted more widely - I have an RFC queued up that would add a similar interface for sending "events", for example
