### ISSUE TITLE
Bug Report: v19 tablet server config parsing incorrect

### ISSUE THREAD

**Issue by shanth96** [vitessio/vitess#16392]
### Overview of the Issue

We're trying to validate v19 to upgrade our clusters and we noticed that Vitess is unable to boot up and gets stuck in a loop with the following errors:
```
E0711 13:57:16.790079       1 state_manager.go:294] Error transitioning to the desired state: REPLICA, Serving, will keep retrying: Code: DEADLINE_EXCEEDED
resource pool context already expired
I0711 13:57:16.790091       1 state_manager.go:745] State: exiting lameduck
E0711 13:57:16.790096       1 tm_state.go:331] Cannot start query service: Code: DEADLINE_EXCEEDED
```

While digging into this, we noticed that the errors were happening because `schemaChangeReloadTimeout` was being set to 0s (even though default is 30s and we don't explicitly configure it). This was causing the DEADLINE_EXCEEDED errors when trying to open the schema engine [here](https://github.com/vitessio/vitess/blob/2c56724549a0fe9262a10ea5e8ffad8594d51a29/go/vt/vttablet/tabletserver/schema/engine.go#L409)

Upon further investigation, we noticed that the `initConfig` section of vttablet had some weird behaviour:

### Reproduction Steps

The code  below is a simple reproduction of the `initConfig` code [here](https://github.com/vitessio/vitess/blob/2c56724549a0fe9262a10ea5e8ffad8594d51a29/go/cmd/vttablet/cli/cli.go#L183).

Running this in v18 vs v19 produces two different results:

```
package main

import (
	"fmt"
	"os"

	"vitess.io/vitess/go/vt/vttablet/tabletserver/tabletenv"
	"vitess.io/vitess/go/yaml2"
)

var tabletConfig = "<path_to_sample_config>"

func main() {
	config := tabletenv.NewDefaultConfig()
	gotBytes, _ := yaml2.Marshal(config)
	fmt.Printf("Config before unmarshaling:\n%s", gotBytes)

	bytes, err := os.ReadFile(tabletConfig)
	if err != nil {
		panic(err)
	}
	if err := yaml2.Unmarshal(bytes, config); err != nil {
		panic(err)
	}

	gotBytes, _ = yaml2.Marshal(config)
	fmt.Printf("Loaded config file %s successfully:\n%s", tabletConfig, gotBytes)
}
```

where tablet-config.yaml is a simple yaml file with any config:
```
consolidator: enable
```

on v19, we get the following output:

```
Config before unmarshaling:
consolidator: enable
consolidatorStreamQuerySize: 2097152
consolidatorStreamTotalSize: 134217728
gracePeriods: {}
healthcheck:
  degradedThresholdSeconds: 30s
  intervalSeconds: 20s
  unhealthyThresholdSeconds: 2h0m0s
hotRowProtection:
  maxConcurrency: 5
  maxGlobalQueueSize: 1000
  maxQueueSize: 20
  mode: disable
messagePostponeParallelism: 4
olap:
  txTimeoutSeconds: 30s
olapReadPool:
  idleTimeoutSeconds: 30m0s
  size: 200
oltp:
  maxRows: 10000
  queryTimeoutSeconds: 30s
  txTimeoutSeconds: 30s
oltpReadPool:
  idleTimeoutSeconds: 30m0s
  size: 16
queryCacheDoorkeeper: true
queryCacheMemory: 33554432
replicationTracker:
  heartbeatIntervalSeconds: 250ms
  mode: disable
rowStreamer:
  maxInnoDBTrxHistLen: 1000000
  maxMySQLReplLagSecs: 43200
schemaChangeReloadTimeout: 30s
schemaReloadIntervalSeconds: 30m0s
signalWhenSchemaChange: true
streamBufferSize: 32768
txPool:
  idleTimeoutSeconds: 30m0s
  size: 20
  timeoutSeconds: 1s

Loaded config file /Users/shanth/src/github.com/Shopify/vitess/go/cmd/vttablet/main/tablet-config.yaml successfully:
consolidator: enable
consolidatorStreamQuerySize: 2097152
consolidatorStreamTotalSize: 134217728
gracePeriods: {}
healthcheck:
  degradedThresholdSeconds: 30s
  intervalSeconds: 20s
  unhealthyThresholdSeconds: 2h0m0s
hotRowProtection:
  maxConcurrency: 5
  maxGlobalQueueSize: 1000
  maxQueueSize: 20
  mode: disable
messagePostponeParallelism: 4
olap:
  txTimeoutSeconds: 30s
olapReadPool:
  idleTimeoutSeconds: 30m0s
  size: 200
oltp:
  maxRows: 10000
  queryTimeoutSeconds: 30s
  txTimeoutSeconds: 30s
oltpReadPool:
  idleTimeoutSeconds: 30m0s
  size: 16
queryCacheDoorkeeper: true
queryCacheMemory: 33554432
replicationTracker:
  heartbeatIntervalSeconds: 250ms
  mode: disable
rowStreamer:
  maxInnoDBTrxHistLen: 1000000
  maxMySQLReplLagSecs: 43200
signalWhenSchemaChange: true
streamBufferSize: 32768
txPool:
  idleTimeoutSeconds: 30m0s
  size: 20
  timeoutSeconds: 1s
```

vs. on v18, we get:
```
Config before unmarshaling:
consolidator: enable
consolidatorStreamQuerySize: 2097152
consolidatorStreamTotalSize: 134217728
gracePeriods: {}
healthcheck:
  degradedThresholdSeconds: 30s
  intervalSeconds: 20s
  unhealthyThresholdSeconds: 2h0m0s
hotRowProtection:
  maxConcurrency: 5
  maxGlobalQueueSize: 1000
  maxQueueSize: 20
  mode: disable
messagePostponeParallelism: 4
olap:
  txTimeoutSeconds: 30s
olapReadPool:
  idleTimeoutSeconds: 30m0s
  size: 200
oltp:
  maxRows: 10000
  queryTimeoutSeconds: 30s
  txTimeoutSeconds: 30s
oltpReadPool:
  idleTimeoutSeconds: 30m0s
  maxWaiters: 5000
  size: 16
queryCacheDoorkeeper: true
queryCacheMemory: 33554432
replicationTracker:
  heartbeatIntervalSeconds: 250ms
  mode: disable
rowStreamer:
  maxInnoDBTrxHistLen: 1000000
  maxMySQLReplLagSecs: 43200
schemaChangeReloadTimeout: 30s
schemaReloadIntervalSeconds: 30m0s
signalWhenSchemaChange: true
streamBufferSize: 32768
txPool:
  idleTimeoutSeconds: 30m0s
  maxWaiters: 5000
  size: 20
  timeoutSeconds: 1s

Loaded config file /Users/shanth/src/github.com/Shopify/vitess/go/cmd/vttablet/main/tablet-config.yaml successfully:
consolidator: enable
consolidatorStreamQuerySize: 2097152
consolidatorStreamTotalSize: 134217728
gracePeriods: {}
healthcheck:
  degradedThresholdSeconds: 30s
  intervalSeconds: 20s
  unhealthyThresholdSeconds: 2h0m0s
hotRowProtection:
  maxConcurrency: 5
  maxGlobalQueueSize: 1000
  maxQueueSize: 20
  mode: disable
messagePostponeParallelism: 4
olap:
  txTimeoutSeconds: 30s
olapReadPool:
  idleTimeoutSeconds: 30m0s
  size: 200
oltp:
  maxRows: 10000
  queryTimeoutSeconds: 30s
  txTimeoutSeconds: 30s
oltpReadPool:
  idleTimeoutSeconds: 30m0s
  maxWaiters: 5000
  size: 16
queryCacheDoorkeeper: true
queryCacheMemory: 33554432
replicationTracker:
  heartbeatIntervalSeconds: 250ms
  mode: disable
rowStreamer:
  maxInnoDBTrxHistLen: 1000000
  maxMySQLReplLagSecs: 43200
schemaChangeReloadTimeout: 30s
schemaReloadIntervalSeconds: 30m0s
signalWhenSchemaChange: true
streamBufferSize: 32768
txPool:
  idleTimeoutSeconds: 30m0s
  maxWaiters: 5000
  size: 20
  timeoutSeconds: 1s
```

Particularly, note how schemaChangeReloadTimeout is not present as a config variable in v19 after unmarshaling.

### Binary Version

```sh
Testing on v19.0.4 and v18.0.5
```

### Operating System and Environment details

```sh
N/A
```
