### ISSUE TITLE
Bug Report: Schema changes fail after 3h due to no heartbeat

### ISSUE THREAD

**Issue by siddharth16396** [vitessio/vitess#18391]
### Issue Observed
We are doing some long running schema changes and noticing that the Schema change is progressing but liveness_timestamp is never incrementing which is eventually leading to the schema change workflows failing exactly at the the 3 hour mark with error:

schema migration failed for shards: [shard: -80, message: stale migration UUID: found running but indicates no liveness in the past 180 minutes], [shard: 80-, message: stale migration UUID: found running but indicates no liveness in the past 180 minutes]

On checking the _vt.schema_migrations table we saw that "liveness_timestamp" never got updated.

```
mysql> SELECT      *    FROM _vt.schema_migrations   where migration_uuid='c7bf500e_4d9e_11f0_ba71_08c0eb8c9084'\G
*************************** 1. row ***************************
                             id: 39
                 migration_uuid: c7bf500e_4d9e_11f0_ba71_08c0eb8c9084
                       keyspace: keshav_test
                          shard: 80-
                   mysql_schema: keshav_test
                    mysql_table: hdfs_reduction_request_info_staging_test
            migration_statement: alter table hdfs_reduction_request_info_staging_test add key idx_hive_database_name_staging (hive_database_name)
                       strategy: vitess
                        options:
                added_timestamp: 2025-06-20 06:21:19
            requested_timestamp: 2025-06-20 06:21:20
                ready_timestamp: NULL
              started_timestamp: 2025-06-20 06:21:21
             liveness_timestamp: 2025-06-20 06:21:35
            completed_timestamp: NULL
              cleanup_timestamp: NULL
               migration_status: running
                       log_path:
                      artifacts: _vt_vrp_c7bf500e4d9e11f0ba7108c0eb8c9084_20250620062121_,
                        retries: 0
                         tablet: dca-0000006278
                 tablet_failure: 0
                       progress: 6.77938
              migration_context: 13004464-9d77-4eb1-8cba-3116a7fe3b93
                     ddl_action: alter
                        message:
              message_timestamp: NULL
                    eta_seconds: 7755
                    rows_copied: 12823760
                     table_rows: 189158340
              added_unique_keys: 0
            removed_unique_keys: 0
                       log_file:
       retain_artifacts_seconds: 86400
            postpone_completion: 0
       removed_unique_key_names:
dropped_no_default_column_names:
          expanded_column_names:
               revertible_notes:
               allow_concurrent: 0
                  reverted_uuid:
                        is_view: 0
              ready_to_complete: 0
      vitess_liveness_indicator: 1750400493
            user_throttle_ratio: 0
                   special_plan:
       last_throttled_timestamp: NULL
            component_throttled:
               reason_throttled:
            cancelled_timestamp: NULL
                postpone_launch: 0
                          stage:
               cutover_attempts: 0
         is_immediate_operation: 0
             reviewed_timestamp: 2025-06-20 06:21:21
    ready_to_complete_timestamp: NULL
      removed_foreign_key_names:
 last_cutover_attempt_timestamp: NULL
                  force_cutover: 0
1 row in set (0.00 sec)

mysql> SELECT      *    FROM _vt.schema_migrations   where migration_uuid='c7bf500e_4d9e_11f0_ba71_08c0eb8c9084'\G
*************************** 1. row ***************************
                             id: 39
                 migration_uuid: c7bf500e_4d9e_11f0_ba71_08c0eb8c9084
                       keyspace: keshav_test
                          shard: 80-
                   mysql_schema: keshav_test
                    mysql_table: hdfs_reduction_request_info_staging_test
            migration_statement: alter table hdfs_reduction_request_info_staging_test add key idx_hive_database_name_staging (hive_database_name)
                       strategy: vitess
                        options:
                added_timestamp: 2025-06-20 06:21:19
            requested_timestamp: 2025-06-20 06:21:20
                ready_timestamp: NULL
              started_timestamp: 2025-06-20 06:21:21
             liveness_timestamp: 2025-06-20 06:21:35
            completed_timestamp: NULL
              cleanup_timestamp: NULL
               migration_status: running
                       log_path:
                      artifacts: _vt_vrp_c7bf500e4d9e11f0ba7108c0eb8c9084_20250620062121_,
                        retries: 0
                         tablet: dca-0000006278
                 tablet_failure: 0
                       progress: 11.3519
              migration_context: 13004464-9d77-4eb1-8cba-3116a7fe3b93
                     ddl_action: alter
                        message:
              message_timestamp: NULL
                    eta_seconds: 7216
                    rows_copied: 21473000
                     table_rows: 189158340
              added_unique_keys: 0
            removed_unique_keys: 0
                       log_file:
       retain_artifacts_seconds: 86400
            postpone_completion: 0
       removed_unique_key_names:
dropped_no_default_column_names:
          expanded_column_names:
               revertible_notes:
               allow_concurrent: 0
                  reverted_uuid:
                        is_view: 0
              ready_to_complete: 0
      vitess_liveness_indicator: 1750400493
            user_throttle_ratio: 0
                   special_plan:
       last_throttled_timestamp: NULL
            component_throttled:
               reason_throttled:
            cancelled_timestamp: NULL
                postpone_launch: 0
                          stage:
               cutover_attempts: 0
         is_immediate_operation: 0
             reviewed_timestamp: 2025-06-20 06:21:21
    ready_to_complete_timestamp: NULL
      removed_foreign_key_names:
 last_cutover_attempt_timestamp: NULL
                  force_cutover: 0
1 row in set (0.00 sec)
```

### RCA
Some long-running VReplication operations (especially during the table copy phase) do not send continuous heartbeats, causing them to fail with “no heartbeat activity” errors. This is due to inconsistent heartbeat implementations in different phases of the replication process.

Vitess uses two different heartbeat systems:

✅ Working Heartbeats (Binlog streaming phase — vstreamer.go)
Heartbeats are sent correctly every 900ms via a properly looped timer:

```
for {
    hbTimer.Reset(HeartbeatTime)
    select {
    case <-hbTimer.C:
        injectHeartbeat(...)
    ...
    }
}

```

❌ Broken Heartbeats (Copy phase — rowstreamer.go)
Only one heartbeat is ever sent because the goroutine exits after the first select:

```
go func() {
    select {
    case <-heartbeatTicker.C:
        safeSend(Heartbeat)
    }
}()
```

### Affected Workflows

Do receive heartbeats:
1. Binlog streaming.
2. Catchup phase of Online DDL.
3. Short Online DDL ops.
4. Resharding (after copy phase)

Do not receive heartbeats:
1. Online DDL copy phase on large tables.
2. Table copy phase of MoveTables/Reshard.
3. Any long-running VStreamRows invocation

### 🧬 Code Flow
**Copy Phase (Broken)**

```
vcopier.copyTable()
  → VStreamRows()
    → rowstreamer.streamQuery()
      → ❌ broken heartbeat goroutine
```

Binlog Streaming Phase (Working)

```
vplayer.play()
  → VStream()
    → vstreamer.Stream()
      → ✅ working heartbeat loop
```

### Reproduction Steps

1. Run a long-running OnlineDDL or MoveTables on a large table.
2. Observe heartbeats stop after ~10s.
3. Eventually the operation fails with `stale migration UUID: found running but indicates no liveness in the past 180 minutes`

### Binary Version

```sh
Bug exists even in the current main branch of vitess.
```

### Operating System and Environment details

```sh
Darwin 24.5.0
arm64
```

### Log Fragments

```sh

```
