### ISSUE TITLE
Add annotations value to EtcdCluster in helm chart to make etcd cluster could be managed by clusterwide etcd-operator.

### ISSUE THREAD

**Issue by ch3rub1m** [vitessio/vitess#4758]
#### Feature Description

Add annotations value to EtcdCluster in helm chart to make etcd cluster could be managed by clusterwide etcd-operator.

#### Use Case(s)

```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-{{ $name }}"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  annotations:
  {{ if $clusterWide }}
    etcd.database.coreos.com/scope: clusterwide
  {{ end }}
spec:
...
```
