### ISSUE TITLE
Error in example of installing master branch /helm/vitess using helm3

### ISSUE THREAD

**Issue by vicnoah** [vitessio/vitess#6214]
helm values:

```
config:
  backup:
    enabled: false
    cron:
      schedule: "0 0 * * *"
      suspend: false
    backup_storage_implementation: gcs
    gcs_backup_storage_bucket: vitess-backups
    gcs_backup_storage_root: vtbackups
    gcsSecret: vitess-gcs-creds
    s3_backup_aws_region: us-east-1
    s3_backup_storage_bucket: vitess-backups
    s3_backup_storage_root: vtbackups
    s3_backup_server_side_encryption: AES256
    s3Secret: vitess-s3-creds

topology:
  deploymentType: prod
  globalCell:
    topologyProvider: k8s
    etcd:
      replicas: 3
  cells:
    - name: zone1
      topologyProvider: k8s

      keyspaces:
        - name: "ocs"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 3
      mysqlProtocol:
        enabled: true
        authType: secret
        username: root
        passwordSecret: root-password
      etcd:
        replicas: 3
      vtctld:
        replicas: 1
      vtgate:
        replicas: 3

jobs:
etcd:
  version: "3.3.10"
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
vtctld:
  serviceType: ClusterIP
  vitessTag: helm-2.0.2-0
  resources:
  extraFlags: {}
  secrets: [] # secrets are mounted under /vt/usersecrets/{secretname}
vtgate:
  serviceType: ClusterIP
  vitessTag: helm-2.0.2-0
  resources:
  extraFlags:
    mysql_server_version: "5.7.9-Vitess"
  secrets: [] # secrets are mounted under /vt/usersecrets/{secretname}
vtctlclient:
  vitessTag: helm-2.0.2-0
  extraFlags: {}
  secrets: [] # secrets are mounted under /vt/usersecrets/{secretname}
vtworker:
  vitessTag: helm-2.0.2-0
  extraFlags: {}
  resources:
  secrets: [] # secrets are mounted under /vt/usersecrets/{secretname}
vttablet:
  vitessTag: helm-2.0.2-0
  flavor: mysql56
  mysqlImage: percona:5.7.26
  enableHeartbeat: false
  enableSemisync: false
  useKeyspaceNameAsDbName: true
  extraMyCnf: ""
  mysqlSize: prod
  extraFlags:
    queryserver-config-max-result-size: 10000
    queryserver-config-query-timeout: 30
    queryserver-config-pool-size: 24
    queryserver-config-stream-pool-size: 100
    queryserver-config-transaction-cap: 300
    app_pool_size: 40
    dba_pool_size: 20
  secrets: []

  resources:
    requests:
      cpu: 2
      memory: 4Gi

  mysqlResources:
    requests:
      cpu: 2
      memory: 4Gi
  dataVolumeClaimAnnotations:
  dataVolumeClaimSpec:
    storageClassName: "local-storage-ocs-vitess"
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10Gi
pmm:
  enabled: false
  pmmTag: 1.17.0
  client:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

  server:
    resources:
    dataVolumeClaimAnnotations:
    dataVolumeClaimSpec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
    env:
      disableTelemetry: true
      metricsResolution: 1s
      metricsRetention: 720h
      queriesRetention: 8
      metricsMemory: "600000"
orchestrator:
  enabled: false
  image: vitess/orchestrator:3.1.1
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 350Mi
```
error:

Time | Healthcheck Result
-- | --
May 22, 2020 at 09:26:37 (UTC) | unhealthy: Unknown database 'ocs' (errno 1049) (sqlstate 42000)
May 22, 2020 at 09:26:32 (UTC) | unhealthy: Access denied for user 'vt_app'@'localhost' (using password: NO) (errno 1045) (sqlstate 28000)
May 22, 2020 at 09:25:52 (UTC) | unhealthy: net.Dial(/vtdataroot/tabletdata/mysql.sock) to local server failed: dial unix /vtdataroot/tabletdata/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)

![image](https://user-images.githubusercontent.com/20820831/82654024-ac49f200-9c52-11ea-8ef8-1a06fd1a263c.png)
![image](https://user-images.githubusercontent.com/20820831/82654331-1f536880-9c53-11ea-8330-d8869f88f1cf.png)

![image](https://user-images.githubusercontent.com/20820831/82653857-6d1ba100-9c52-11ea-96d1-53c6c4b2c5a8.png)
