### ISSUE TITLE
SAVEPOINT does not exist: RELEASE SAVEPOINT sa_savepoint_1 (errno 1305)

### ISSUE THREAD

**Issue by Smita8081** [vitessio/vitess#6754]
#### Overview of the Issue
Hi, I am working onto replace usage of MYSQL with vitess cluster for Openstack's core services such as Nova, Neutron, Glance etc.
On integrating Vitess cluster with Nova service of Openstack, I am facing below mentioned error

`Execute: SAVEPOINT does not exist: RELEASE SAVEPOINT sa_savepoint_1 (errno 1305) (sqlstate 42000), request: map[BindVariables:map[] Session:autocommit:true target_string:"nova" options:<included_fields:ALL client_found_rows:true > last_insert_id:1 found_rows:1 row_count:-1 Sql:RELEASE SAVEPOINT sa_savepoint_1]`

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deployed below mentioned Vitess cluster for Nova keyspace:

```
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: nova
spec:
  images:
    vtctld: docker.io/vitess/lite:v7.0.1
    vtgate: docker.io/vitess/lite:v7.0.1
    vttablet: docker.io/vitess/lite:v7.0.1
    vtbackup: docker.io/vitess/lite:v7.0.1
  cells:
  - name: novazone
    gateway:
      authentication:
        static:
          secret:
            name: nova-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  vitessDashboard:
    cells:
    - novazone
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: nova
    turndownPolicy: Immediate
    partitionings:
    - custom:
        shards:
        - databaseInitScriptSecret:
            name: nova-cluster-config
            key: init_db.sql
          keyRange: {}
          replication:
            enforceSemiSync: false
          tabletPools:
          - cell: novazone
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8
                queryserver-config-pool-size: "5"
                queryserver-config-stream-pool-size: "5"
                queryserver-config-transaction-cap: "5"
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
            externalDatastore:
              credentialsSecret:
                key: rds.json
                name: nova-cluster-config
              database: nova
              host: 192.168.1.100
              port: 3306
              user: test
            type: externalmaster
            dataVolumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-cluster-config
type: Opaque
stringData:
  rds.json: |
    { "test": [ "password" ] }
  users.json: |
    {
      "nova": [{
        "UserData": "nova",
        "Password": "password"
      }]
    }
  init_db.sql: |
# Empty
# #
#

```
2. After deployment used VtGate service's IP and keyspace name in Nova's value.yaml to connect to Vitess cluster.
3. Redeployed helm chart deployment of Nova service in kubernetes cluster.
4. Logs of Nova service, vtgate, vttablet were fine after deployment. To test Nova service's functionality I created instance in Openstack and it failed.

Error log reflected in VtGate:

`Execute: SAVEPOINT does not exist: RELEASE SAVEPOINT sa_savepoint_1 (errno 1305) (sqlstate 42000), request: map[BindVariables:map[] Session:autocommit:true target_string:"nova" options:<included_fields:ALL client_found_rows:true > last_insert_id:1 found_rows:1 row_count:-1 Sql:RELEASE SAVEPOINT sa_savepoint_1]`
