### ISSUE TITLE
Vitess Operator (VitessCluster) - setting mysql80Compatible and using mysql80 images still results in mysqld 5.7

### ISSUE THREAD

**Issue by jai** [vitessio/vitess#8602]
Hi - not sure if I'm missing something on how to set up Vitess Operator to use MySQL 8.0?

Ref Slack thread: https://vitess.slack.com/archives/CNE9WP677/p1628481964005800

#### Overview of the Issue

Using the Vitess Operator to set up a `VitessCluster` with the following spec:

```yaml
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: test-mysql8-retest-05
spec:
  images:
    vtctld: vitess/lite:mysql80
    vtgate: vitess/lite:mysql80
    vttablet: vitess/lite:mysql80
    vtbackup: vitess/lite:mysql80
    mysqld:
      mysql80Compatible: vitess/lite:mysql80
    mysqldExporter: prom/mysqld-exporter:v0.11.0
...
```

The `mysqld` version running on the `vttablet` and `vtctld` Pods still return their version as 5.7.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Create a `VitessCluster` resource using the above spec/images
1. Connect in to the terminal of any `vttablet` or `vtctld` Pod
1. Run the following command and receive the given output:
```shell
$ /usr/sbin/mysqld --version
/usr/sbin/mysqld  Ver 5.7.31 for Linux on x86_64 (MySQL Community Server (GPL))
```

#### Binary version

Using the [Vitess operator.yaml from **main**](https://github.com/vitessio/vitess/blob/main/examples/operator/operator.yaml)

#### Operating system and Environment details

Running on AWS EKS.
