### ISSUE TITLE
Error Running the 101_init_cluster.yaml

### ISSUE THREAD

**Issue by tonycoder0525** [vitessio/vitess#9141]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [Vitess User Guide](https://vitess.io/user-guide/introduction/)
- Any other questions can be asked in the community [Slack workspace](https://vitess.io/slack)

I was trying to follow the guide on [Vitess Operator for Kubernetes](https://vitess.io/docs/get-started/operator/) and ran it on k8s v1.19.8, I found that it requires PersistantVolumnClaim and I added, modified as follows:

```yaml
# The following example is minimalist. The security policies
# and resource specifications are not meant to be used in production.
# Please refer to the operator documentation for recommendations on
# production settings.
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  images:
    vtctld: vitess/lite:v12.0.0
    vtgate: vitess/lite:v12.0.0
    vttablet: vitess/lite:v12.0.0
    vtbackup: vitess/lite:v12.0.0
    mysqld:
      mysql56Compatible: vitess/lite:v12.0.0
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: zone1
    gateway:
      authentication:
        static:
          secret:
            name: example-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  globalLockserver:
    etcd:
      dataVolumeClaimTemplate:
        accessModes: ["ReadWriteOnce"]
        storageClassName: vitess-local
        resources:
          requests:
            storage: 10Gi
  vitessDashboard:
    cells:
    - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: commerce
    turndownPolicy: Immediate
    partitionings:
    - equal:
        parts: 1
        shardTemplate:
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
          tabletPools:
          - cell: zone1
            type: replica
            replicas: 2
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            mysqld:
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            dataVolumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              storageClassName: vitess-local
              resources:
                requests:
                  storage: 10Gi
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: example-cluster-config
type: Opaque
stringData:
  users.json: |
    {
      "user": [{
        "UserData": "user",
        "Password": ""
      }]
    }
  init_db.sql: |
    # This file is executed immediately after mysql_install_db,
    # to initialize a fresh data directory.

    ###############################################################################
    # Equivalent of mysql_secure_installation
    ###############################################################################

    # Changes during the init db should not make it to the binlog.
    # They could potentially create errant transactions on replicas.
    SET sql_log_bin = 0;
    # Remove anonymous users.
    DELETE FROM mysql.user WHERE User = '';

    # Disable remote root access (only allow UNIX socket).
    DELETE FROM mysql.user WHERE User = 'root' AND Host != 'localhost';

    # Remove test database.
    DROP DATABASE IF EXISTS test;
    
    create database abc;

    ###############################################################################
    # Vitess defaults
    ###############################################################################

    # Vitess-internal database.
    CREATE DATABASE IF NOT EXISTS _vt;
    # Note that definitions of local_metadata and shard_metadata should be the same
    # as in production which is defined in go/vt/mysqlctl/metadata_tables.go.
    CREATE TABLE IF NOT EXISTS _vt.local_metadata (
      name VARCHAR(255) NOT NULL,
      value VARCHAR(255) NOT NULL,
      db_name VARBINARY(255) NOT NULL,
      PRIMARY KEY (db_name, name)
      ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS _vt.shard_metadata (
      name VARCHAR(255) NOT NULL,
      value MEDIUMBLOB NOT NULL,
      db_name VARBINARY(255) NOT NULL,
      PRIMARY KEY (db_name, name)
      ) ENGINE=InnoDB;

    # Admin user with all privileges.
    CREATE USER 'vt_dba'@'localhost';
    GRANT ALL ON *.* TO 'vt_dba'@'localhost';
    GRANT GRANT OPTION ON *.* TO 'vt_dba'@'localhost';

    # User for app traffic, with global read-write access.
    CREATE USER 'vt_app'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_app'@'localhost';

    # User for app debug traffic, with global read access.
    CREATE USER 'vt_appdebug'@'localhost';
    GRANT SELECT, SHOW DATABASES, PROCESS ON *.* TO 'vt_appdebug'@'localhost';

    # User for administrative operations that need to be executed as non-SUPER.
    # Same permissions as vt_app here.
    CREATE USER 'vt_allprivs'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_allprivs'@'localhost';

    # User for slave replication connections.
    # TODO: Should we set a password on this since it allows remote connections?
    CREATE USER 'vt_repl'@'%';
    GRANT REPLICATION SLAVE ON *.* TO 'vt_repl'@'%';

    # User for Vitess filtered replication (binlog player).
    # Same permissions as vt_app.
    CREATE USER 'vt_filtered'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_filtered'@'localhost';

    # User for Orchestrator (https://github.com/openark/orchestrator).
    # TODO: Reenable when the password is randomly generated.
    #CREATE USER 'orc_client_user'@'%' IDENTIFIED BY 'orc_client_user_password';
    #GRANT SUPER, PROCESS, REPLICATION SLAVE, RELOAD
    #  ON *.* TO 'orc_client_user'@'%';
    #GRANT SELECT
    #  ON _vt.* TO 'orc_client_user'@'%';

    FLUSH PRIVILEGES;

    RESET SLAVE ALL;
    RESET MASTER;
```

And it is just fine for me when I check `kubectl get pod`:
```shell
NAME                                             READY   STATUS    RESTARTS   AGE
example-etcd-faf13de3-1                          1/1     Running   0          58m
example-etcd-faf13de3-2                          1/1     Running   0          58m
example-etcd-faf13de3-3                          1/1     Running   0          58m
example-vttablet-zone1-2469782763-bfadd780       3/3     Running   1          58m
example-vttablet-zone1-2548885007-46a852d0       3/3     Running   1          58m
example-zone1-vtctld-1d4dcad0-569b64b9b8-p6v8t   1/1     Running   1          58m
example-zone1-vtgate-bc6cde92-79765c9d98-xzjrl   1/1     Running   1          58m
vitess-operator-7ccd86b994-vppbz                 1/1     Running   0          58m
```
I also ran `./pf.sh &`, made the alias.
However, when I tried to continue to run `vtctlclient ApplySchema -sql="$(cat create_commerce_schema.sql)" commerce`
Error occurs:
```shell
[root@k8s-master operator]# vtctlclient ApplySchema -sql="$(cat create_commerce_schema.sql)" commerce
ApplySchema Error: rpc error: code = Unknown desc = schema change failed, ExecuteResult: {
  "FailedShards": null,
  "SuccessShards": null,
  "CurSQLIndex": 0,
  "Sqls": [
    "create table product(\n  sku varbinary(128),\n  description varbinary(128),\n  price bigint,\n  primary key(sku)\n) ENGINE=InnoDB",
    "create table customer(\n  customer_id bigint not null auto_increment,\n  email varbinary(128),\n  primary key(customer_id)\n) ENGINE=InnoDB",
    "create table corder(\n  order_id bigint not null auto_increment,\n  customer_id bigint,\n  sku varbinary(128),\n  price bigint,\n  primary key(order_id)\n) ENGINE=InnoDB"
  ],
  "ExecutorErr": "rpc error: code = Unknown desc = TabletManager.PreflightSchema on zone1-2469782763 error: EOF (errno 2013) (sqlstate HY000) during query: SELECT * FROM `_vt_preflight`.`product` WHERE 1=0\ncontext canceled: EOF (errno 2013) (sqlstate HY000) during query: SELECT * FROM `_vt_preflight`.`product` WHERE 1=0\ncontext canceled",
  "TotalTimeSpent": 402451194
}
E1104 16:50:50.187328    5541 main.go:76] remote error: rpc error: code = Unknown desc = schema change failed, ExecuteResult: {
  "FailedShards": null,
  "SuccessShards": null,
  "CurSQLIndex": 0,
  "Sqls": [
    "create table product(\n  sku varbinary(128),\n  description varbinary(128),\n  price bigint,\n  primary key(sku)\n) ENGINE=InnoDB",
    "create table customer(\n  customer_id bigint not null auto_increment,\n  email varbinary(128),\n  primary key(customer_id)\n) ENGINE=InnoDB",
    "create table corder(\n  order_id bigint not null auto_increment,\n  customer_id bigint,\n  sku varbinary(128),\n  price bigint,\n  primary key(order_id)\n) ENGINE=InnoDB"
  ],
  "ExecutorErr": "rpc error: code = Unknown desc = TabletManager.PreflightSchema on zone1-2469782763 error: EOF (errno 2013) (sqlstate HY000) during query: SELECT * FROM `_vt_preflight`.`product` WHERE 1=0\ncontext canceled: EOF (errno 2013) (sqlstate HY000) during query: SELECT * FROM `_vt_preflight`.`product` WHERE 1=0\ncontext canceled",
  "TotalTimeSpent": 402451194
}
``` 

It seems to me that when the cluster is initializing, the init_db.sql did not run, for I have tried to add something into it and it didn't work. Now I wonder how could I continue to run this example.
