### ISSUE TITLE
General error: 1815 [BUG] unrecognized prepare statement

### ISSUE THREAD

**Issue by droslean** [vitessio/vitess#9445]
```console
[2021-12-28 01:46:36] staging.ERROR: CrudException: SQLSTATE[HY000]: General error: 1815 [BUG] unrecognized prepare statement: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `bonuses` where `bonuses`.`parent_id` in (413, 414)) union all (select `bonuses`.*, `depth` + 1 as `depth`, concat(`path`, ?, `bonuses`.`id`) from `bonuses` inner join `laravel_cte` on `laravel_cte`.`id` = `bonuses`.`parent_id`)) select * from `laravel_cte` (SQL: with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `bonuses` where `bonuses`.`parent_id` in (413, 414)) union all (select `bonuses`.*, `depth` + 1 as `depth`, concat(`path`, ., `bonuses`.`id`) from `bonuses` inner join `laravel_cte` on `laravel_cte`.`id` = `bonuses`.`parent_id`)) select * from `laravel_cte`)  
```

I am using vitess operator on Kubernetes with images: `vitess/lite:latest`

```yaml
spec:
  images:
    vtctld: vitess/lite:latest
    vtgate: vitess/lite:latest
    vttablet: vitess/lite:latest
    vtbackup: vitess/lite:latest
    mysqld:
      mysql80Compatible: vitess/lite:mysql80
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: zone1
    gateway:
      extraFlags:
        mysql_server_version: 8.0.11
      authentication:
        static:
          secret:
            name: cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
```
