### ISSUE TITLE
Adding unmanaged tablet to a Kubernetes cluster

### ISSUE THREAD

**Issue by raftx24** [vitessio/vitess#9446]
Hey.
I configured an unmanaged tablet with a local operator, but how can I do this with the k8s operator? I tried to run similar command on a pod and it worked for a few minutes and after some minutes I got this error.
```
E1228 08:56:20.289344     371 shard_sync.go:110] Failed to sync shard record: node doesn't exist: /vitess/test/global/keyspaces/testdb/shards/-/Shard
I1228 08:56:50.289431     371 shard_sync.go:73] Retry sync
E1228 08:56:50.290017     371 shard_sync.go:110] Failed to sync shard record: node doesn't exist: /vitess/test/global/keyspaces/testdb/shards/-/Shard
I1228 08:57:20.291073     371 shard_sync.go:73] Retry sync
E1228 08:57:20.291708     371 shard_sync.go:110] Failed to sync shard record: node doesn't exist: /vitess/test/global/keyspaces/testdb/shards/-/Shard
I1228 08:57:50.292048     371 shard_sync.go:73] Retry sync
E1228 08:57:50.292616     371 shard_sync.go:110] Failed to sync shard record: node doesn't exist: /vitess/test/global/keyspaces/testdb/shards/-/Shard
```

**Comment by raftx24** [comment]
I found this:
```
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: test
spec:
  images:
    vtctld: vitess/lite:v12.0.0-mysql80
    vtgate: vitess/lite:v12.0.0-mysql80
    vttablet: vitess/lite:v12.0.0-mysql80
    vtbackup: vitess/lite:v12.0.0-mysql80
    mysqld:
      mysql56Compatible: vitess/lite:v12.0.0-mysql80
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: zone1
    gateway:
      authentication:
        static:
          secret:
            name: test-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 1000Mi
        limits:
          memory: 1000Mi
  vitessDashboard:
    cells:
    - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
  keyspaces:
  - name: test
    turndownPolicy: Immediate
    partitionings:
      - equal:
          parts: 1
          shardTemplate:
            databaseInitScriptSecret:
              name: test-cluster-config
              key: init_db.sql
            replication:
              enforceSemiSync: false
            tabletPools:
              - cell: zone1
                type: externalmaster
                replicas: 1
                vttablet:
                  extraFlags:
                    db_charset: utf8mb4
                  resources:
                    limits:
                      memory: 1000Mi
                    requests:
                      cpu: 500m
                      memory: 1000Mi
                mysqld:
                  resources:
                    limits:
                      memory: 1000Mi
                    requests:
                      cpu: 500m
                      memory: 1000Mi
                externalDatastore:
                  credentialsSecret:
                    name: test-cluster-config
                    key: db_cred.json
                  database: test_staging_test
                  user: DB_USER
                  host: HOST
                  port: PORT
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 2Gi
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: test-cluster-config
type: Opaque
stringData:
  db_cred.json: |
    {
      "DB_USER": ["DB_PASSWORD"]
    }

```
