### ISSUE TITLE
cp: cannot stat '/vt/bin/mysqlctld': No such file or directory

### ISSUE THREAD

**Issue by droslean** [vitessio/vitess#9455]
```console
NAME                                           READY   STATUS                  RESTARTS   AGE
my-db-etcd-ef78da7d-1                          1/1     Running                 0          7d15h
my-db-etcd-ef78da7d-2                          1/1     Running                 0          7d15h
my-db-etcd-ef78da7d-3                          1/1     Running                 0          7d15h
my-db-vttablet-zone1-1407048482-bd9db5f2       0/3     Init:CrashLoopBackOff   5          4m19s
my-db-vttablet-zone1-1563904368-16ebd7f6       0/3     Init:CrashLoopBackOff   5          4m12s
my-db-zone1-vtctld-0de28170-b5cb8894b-k8znj    1/1     Running                 0          6m20s
my-db-zone1-vtgate-6926eeba-5db759d8c6-q8p5n   1/1     Running                 0          6m20s
vitess-operator-6dff974b75-zdvzz               1/1     Running                 0          7d15h
```

```console
$ kubectl logs ginbits-db-vttablet-zone1-1563904368-16ebd7f6 -c init-vt-root
+ mkdir -p /mnt/vt/bin
+ cp --no-clobber /vt/bin/mysqlctld /mnt/vt/bin/
cp: cannot stat '/vt/bin/mysqlctld': No such file or directory
```

I am using vitess operator image: `planetscale/vitess-operator:latest`

Cluster config images:
```yaml
...
spec:
  images:
    vtctld: vitess/lite:latest
    vtgate: vitess/lite:latest
    vttablet: vitess/lite:latest
    vtbackup: vitess/lite:latest
...
```
