### ISSUE TITLE
General error: 1105 unknown error: syntax error at position 5 near 'with'

### ISSUE THREAD

**Issue by droslean** [vitessio/vitess#9459]
```sql
with recursive `laravel_cte` as ((select *, 1 as `depth`, cast(`id` as char(65535)) as `path` from `bonuses` where `bonuses`.`parent_id` in (413, 414)) union all (select `bonuses`.*, `depth` + 1 as `depth`, concat(`path`, ., `bonuses`.`id`) from `bonuses` inner join `laravel_cte` on `laravel_cte`.`id` = `bonuses`.`parent_id`)) select * from `laravel_cte`
```

```yaml
  images:
    vtctld: vitess/lite:v12.0.0-mysql80
    vtgate: vitess/lite:v12.0.0-mysql80
    vttablet: vitess/lite:v12.0.0-mysql80
    vtbackup: vitess/lite:v12.0.0-mysql80
    mysqld:
      mysql80Compatible: vitess/lite:v12.0.0-mysql80
```

Related to https://github.com/vitessio/vitess/issues/4099
